# Generated by Django 5.0.1 on 2024-03-28 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoanAppForm',
            fields=[
                ('app_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Application No')),
                ('app_date', models.DateField(verbose_name='Application Date')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11, verbose_name='IFSC code')),
                ('account_number', models.CharField(max_length=20)),
                ('micr_code', models.CharField(max_length=9, verbose_name='MICR code')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_adhaar', models.FileField(upload_to='documents/', verbose_name='Applicant Adhaar(Masked and signed-OSV)')),
                ('applicant_pan', models.FileField(upload_to='documents/', verbose_name='Applicant PAN(Signed-OSV)')),
                ('applicant_form_sixty', models.FileField(upload_to='documents/', verbose_name='Applicant Form-60(Signed-OSV)(if no PAN)')),
                ('applicant_voter_id', models.FileField(upload_to='documents/', verbose_name='Applicant Voter  Id(Optional)')),
                ('co_applicant_adhaar', models.FileField(upload_to='documents/', verbose_name='Co-Applicant Adhaar(Masked and signed)')),
                ('co_applicant_pan', models.FileField(upload_to='documents/', verbose_name='Co-Applicant PAN(Signed)')),
                ('bankers_verification', models.FileField(upload_to='documents/', verbose_name='Bankers Verification')),
                ('indemnity_bond_signature', models.FileField(upload_to='documents/', verbose_name='Indemnity bond - signature /name/dob(With notorized affidavit)')),
                ('milk_statement', models.FileField(upload_to='documents/', verbose_name='Milk statement')),
                ('bank_statement', models.FileField(upload_to='documents/', verbose_name='Bank statement')),
                ('living_certificate', models.FileField(upload_to='documents/', verbose_name='Living certificate')),
                ('nach_mandate', models.FileField(upload_to='documents/', verbose_name='NACH Mandate')),
                ('spdc_pdc_cheques', models.FileField(upload_to='documents/', verbose_name='SPDC/PDC Cheques(Applicant & co-applicant)')),
                ('address_proof', models.FileField(upload_to='documents/', verbose_name='Address proof(ration card, electricity bill, pahani, gas cylender book, etc..)')),
                ('anexure', models.FileField(upload_to='documents/', verbose_name='Anexure')),
                ('vernacular_signature', models.FileField(upload_to='documents/', verbose_name='Vernacular Signature')),
                ('ndc_checklist', models.FileField(upload_to='documents/', verbose_name='NDC Checklist')),
                ('login_checklist', models.FileField(upload_to='documents/', verbose_name='LoginChecklist')),
                ('loan_agreement', models.FileField(upload_to='documents/', verbose_name='LOAN Agreement')),
                ('audit_trail', models.FileField(upload_to='documents/', verbose_name='Audit Trail')),
                ('loan_deduction_table', models.FileField(upload_to='documents/', verbose_name='Loan deduction Table')),
                ('insurance', models.FileField(upload_to='documents/', verbose_name='Insurance')),
                ('field_visit_photo', models.FileField(upload_to='documents/', verbose_name='Field visit photo(Home, cattle,shed)')),
                ('cam_sheet', models.FileField(upload_to='documents/', verbose_name='CAM sheet')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_or_spouse_name', models.CharField(max_length=100, verbose_name="Father/Spouse's Name")),
                ('pan_number', models.CharField(max_length=10, verbose_name='PAN No')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('address_1', models.CharField(max_length=200, verbose_name='Address 1')),
                ('state_1', models.CharField(max_length=100, verbose_name='State')),
                ('city_1', models.CharField(max_length=100, verbose_name='City')),
                ('pincode_1', models.CharField(max_length=10, verbose_name='Pincode')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address 2')),
                ('state_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='State 2')),
                ('city_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='City 2')),
                ('pincode_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode 2')),
                ('ownership_status', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented')], max_length=100)),
                ('applicant_photo', models.ImageField(upload_to='applicant_photos/', verbose_name='Applicant photo(signed)')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='CoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_or_spouse_name', models.CharField(max_length=100, verbose_name="Father/Spouse's Name")),
                ('pan_number', models.CharField(max_length=10, verbose_name='PAN No')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('address_1', models.CharField(max_length=200, verbose_name='Address 1')),
                ('state_1', models.CharField(max_length=100, verbose_name='State')),
                ('city_1', models.CharField(max_length=100, verbose_name='City')),
                ('pincode_1', models.CharField(max_length=10, verbose_name='Pincode')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address 2')),
                ('state_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='State 2')),
                ('city_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='City 2')),
                ('pincode_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode 2')),
                ('ownership_status', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented')], max_length=100)),
                ('applicant_photo', models.ImageField(upload_to='applicant_photos/', verbose_name='Applicant photo(signed)')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Applied Amount INR')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_loan', models.CharField(max_length=50, verbose_name='Purpose of loan')),
                ('loan_type', models.CharField(max_length=50, verbose_name='Application Date')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan amount')),
                ('desire_tenure', models.IntegerField(verbose_name='Desire Tenure')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='GstDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceApplicationToAmbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('loan_facility', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan facility (Rs)')),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Insurance premium (Rs)')),
                ('to_specified_paravet', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='To specified Paravet (Rs)')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceApplicationToSaswat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('loan_facility', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan facility (Rs)')),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Insurance premium (Rs)')),
                ('to_specified_paravet', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='To specified Paravet (Rs)')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='PostDatedCheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no_from', models.IntegerField(verbose_name='Cheque Number From')),
                ('cheque_no_to', models.IntegerField(verbose_name='Cheque Number To')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issuing_bank_name', models.CharField(max_length=30, verbose_name='Issuing bank name')),
                ('issuing_bank_ac_no', models.CharField(max_length=30, verbose_name='Issuing bank Acc Number')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_details', models.CharField(max_length=100)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_details', models.CharField(max_length=100)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='SequrityPostDatedCheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no_from', models.IntegerField(verbose_name='Cheque Number From')),
                ('cheque_no_to', models.IntegerField(verbose_name='Cheque Number To')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issuing_bank_name', models.CharField(max_length=30, verbose_name='Issuing bank name')),
                ('issuing_bank_ac_no', models.CharField(max_length=30, verbose_name='Issuing bank Acc Number')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
        migrations.CreateModel(
            name='SpdcAndPdcForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('loan_agreement_dated', models.DateField()),
                ('name_of_borrower_or_co_borrower', models.CharField(max_length=30, verbose_name='Name of borrower/co-borrower')),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry_app.businessloanappform')),
            ],
        ),
    ]
