# Generated by Django 5.0.3 on 2024-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='address_proof',
            field=models.FileField(upload_to='attachments/', verbose_name='Address proof(ration card, electricity bill, pahani, gas cylender book, etc..)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='anexure',
            field=models.FileField(upload_to='attachments/', verbose_name='Anexure'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='applicant_adhaar',
            field=models.FileField(upload_to='attachments/', verbose_name='Applicant Adhaar(Masked and signed-OSV)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='applicant_form_sixty',
            field=models.FileField(upload_to='attachments/', verbose_name='Applicant Form-60(Signed-OSV)(if no PAN)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='applicant_pan',
            field=models.FileField(upload_to='attachments/', verbose_name='Applicant PAN(Signed-OSV)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='applicant_voter_id',
            field=models.FileField(upload_to='attachments/', verbose_name='Applicant Voter  Id(Optional)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='audit_trail',
            field=models.FileField(upload_to='attachments/', verbose_name='Audit Trail'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='bank_statement',
            field=models.FileField(upload_to='attachments/', verbose_name='Bank statement'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='bankers_verification',
            field=models.FileField(upload_to='attachments/', verbose_name='Bankers Verification'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='cam_sheet',
            field=models.FileField(upload_to='attachments/', verbose_name='CAM sheet'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='co_applicant_adhaar',
            field=models.FileField(upload_to='attachments/', verbose_name='Co-Applicant Adhaar(Masked and signed)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='co_applicant_pan',
            field=models.FileField(upload_to='attachments/', verbose_name='Co-Applicant PAN(Signed)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='field_visit_photo',
            field=models.FileField(upload_to='attachments/', verbose_name='Field visit photo(Home, cattle,shed)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='indemnity_bond_signature',
            field=models.FileField(upload_to='attachments/', verbose_name='Indemnity bond - signature /name/dob(With notorized affidavit)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='insurance',
            field=models.FileField(upload_to='attachments/', verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='living_certificate',
            field=models.FileField(upload_to='attachments/', verbose_name='Living certificate'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='loan_agreement',
            field=models.FileField(upload_to='attachments/', verbose_name='LOAN Agreement'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='loan_deduction_table',
            field=models.FileField(upload_to='attachments/', verbose_name='Loan deduction Table'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='login_checklist',
            field=models.FileField(upload_to='attachments/', verbose_name='LoginChecklist'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='milk_statement',
            field=models.FileField(upload_to='attachments/', verbose_name='Milk statement'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='nach_mandate',
            field=models.FileField(upload_to='attachments/', verbose_name='NACH Mandate'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ndc_checklist',
            field=models.FileField(upload_to='attachments/', verbose_name='NDC Checklist'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='spdc_pdc_cheques',
            field=models.FileField(upload_to='attachments/', verbose_name='SPDC/PDC Cheques(Applicant & co-applicant)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='vernacular_signature',
            field=models.FileField(upload_to='attachments/', verbose_name='Vernacular Signature'),
        ),
    ]
