# Generated by Django 5.0.1 on 2024-02-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('mid_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('work_dept', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_genration_time', models.DateTimeField(auto_now_add=True)),
                ('otp_expiration_time', models.DateTimeField()),
            ],
        ),
    ]
